name: btc_market
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: ^3.3.0

# Packages and plugins from pub.dev
# - To add new packages, run `flutter pub add packageName`
# - To upgrade dependencies, run `flutter pub upgrade packageName`
# - To check for new versions, run `flutter pub outdated`
# Try not to edit this section by hand
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # Firebase packages
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5

  # UI packages
  go_router: ^14.8.1
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1

  # Misc packages
  meta: ^1.11.0
  file_picker: ^9.2.3
  url_launcher: ^6.2.5
  firebase_messaging: ^15.2.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  image_path: "assets/logos/shopbing.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/logos/shopbing.png"
  web:
    generate: true
    image_path: "assets/logos/shopbing.png"
    background_color: "#005A43"
    theme_color: "#005A43"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/categories/
    - assets/bearcat/
    - assets/logos/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
