name: btc_market
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.3.0

# Packages and plugins from pub.dev
# - To add new packages, run `flutter pub add packageName`
# - To upgrade dependencies, run `flutter pub upgrade packageName`
# - To check for new versions, run `flutter pub outdated`
# Try not to edit this section by hand
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter 

  # Firebase packages
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.5
  firebase_storage: ^11.6.7
  cloud_firestore: ^4.15.5

  # UI packages
  go_router: ^13.2.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0

  # Misc packages
  meta: ^1.11.0
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/categories/
    - assets/bearcat/
 
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
