name: btc_market
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.3.0

# Packages and plugins from pub.dev
# - To add new packages, run `flutter pub add packageName`
# - To upgrade dependencies, run `flutter pub upgrade packageName`
# - To check for new versions, run `flutter pub outdated`
# Try not to edit this section by hand
dependencies:
  flutter:
    sdk: flutter
  flutter_social_button: any

  http: ^1.1.0
  cloud_firestore: ^4.12.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  meta: ^1.10.0
  go_router: ^13.2.0
  flutter_rating_bar: ^4.0.1
  # flutter_social_button: ^1.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # 
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
