// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos; 
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsKJxU9wEyhKGIU3YBslMZoe6VheAisdU',
    appId: '1:458210387235:web:7eca713677d204bb8f9896',
    messagingSenderId: '458210387235',
    projectId: 'btc-market-575d9',
    authDomain: 'btc-market-575d9.firebaseapp.com',
    storageBucket: 'btc-market-575d9.appspot.com',
    measurementId: 'G-XKL6KX0N0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRBm2uVFlO4lxUYSAj7n4QxPTTEjRe8uM',
    appId: '1:458210387235:android:eb2a786bd64acb5c8f9896',
    messagingSenderId: '458210387235',
    projectId: 'btc-market-575d9',
    storageBucket: 'btc-market-575d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQDtwOt_p75n2gyRtNrUw1VTWj345EIjA',
    appId: '1:458210387235:ios:98bc0c7cfcaedae28f9896',
    messagingSenderId: '458210387235',
    projectId: 'btc-market-575d9',
    storageBucket: 'btc-market-575d9.appspot.com',
    iosBundleId: 'com.example.btcMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQDtwOt_p75n2gyRtNrUw1VTWj345EIjA',
    appId: '1:458210387235:ios:8c1a113c88597c0e8f9896',
    messagingSenderId: '458210387235',
    projectId: 'btc-market-575d9',
    storageBucket: 'btc-market-575d9.appspot.com',
    iosBundleId: 'com.example.btcMarket.RunnerTests',
  );
}
